run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: siyuan

issues:
  exclude-use-default: false
